= MTL-News|谷歌最终也逃不过华尔街的绞杀？
:uri-google-blog: http://googleblog.blogspot.ca/2015/08/google-alphabet.html

昨天谷歌宣布重组成立新的Alphabet母公司，谷歌将成为Alphabet的子公司。受此消息刺激，谷歌股价盘后大涨。Larry Page在 {uri-google-blog}[谷歌官方Blog] 上面提到重组的原因：

****
Our company is operating well today, but we think we can make it cleaner and more accountable.
****

其实，笔者认为谷歌现在的运营状况并不是很好。7月份的时候，谷歌公司公布的第二季度财报显示净利润同比增长17%，值得一提的是利润的增长部分依赖于公司对开支的缩减。但笔者在其财报中发现，谷歌OPEX（Operating Expense）涨了13.2%。这个缩减怎么来的，笔者也是没法看出个门道了。这几年来google+和google glass，还有一系列其它产品的失败，已经让谷歌元气大伤，更别提来自众多其它公司的竞争。

这一次的重组让谷歌专注于其互联网业务，其它的部分单独划分出来专注于各自的业务（比如长寿项目，X lab等）。看似非常合理的重组，笔者在其中似乎看到了来自于华尔街的虎视眈眈。谷歌拆分出其旗下的不同业务来重组，非常利于其旗下业务的分拆。读者有没有想到AT&T和Lucent的分拆，HP和Agilent的分拆，还有eBay和Paypal的分拆？每一笔分拆，华尔街都可以攫取巨大的利益。

如果真的是这样，那好戏可能才刚刚开始。最终的谷歌可能会越发变小（仅剩其核心业务），从而得以整个公司债券化，或者说是杠杆收购（Leveraged Buyout）。收购方以极高的杠杆，用发行债务借来的钱，对谷歌整体的收购。读者或许以为这些债务会归算到收购方，其实不然，这笔债务会算在谷歌公司上面。无需等待，债权方发行垃圾债券，把贷款的收益出售给其它金融机构。这个手法，大家是否想到了08年的次级抵押贷款？

Alphabet也好，谷歌也好，他们的未来我们现在还无法得知。也许这一次重组是其走向未来巨大成功的转折点，也有可能是其走向衰退的转折点。

Larry Page的原文请戳：
http://googleblog.blogspot.ca/2015/08/google-alphabet.html

