= MTL-News|关于我们，加入我们
:hp-alt-title: about us
:published_at: 2015-08-14
:hp-tags: mtl news
:author: Yucun

MTL-News是一个专注互联网创业的新闻blog。我们的素材以英文文章摘读和点评为主，并附上原文连接，我们也会偶尔写几篇原创文章。文章的来源很广，既有从Techcrunch，Hacker News来的，也有来自个人blog的。原创文章主要是针对蒙特利尔本地的互联网行业，但不限于蒙特利尔。国内的文章不在我们的考虑范围中，因为很多都是翻译自国外的文章，我们鼓励读者直接阅读英文原文。

MTL-News并没有想法要吸引所有的读者，成立这个blog最初的原因也并非是想做成一个新闻媒体。随着来自国内高学历背景的留学生的增多，特别是STEM专业的，我们想借用MTL-News这样一个blog媒介来吸引这一部分留学生。我们希望通过高质量的文章内容，帮助大家了解北美互联网行业的发展，同时汇聚一批有着共同理念的朋友。我和Kevin认为这是确保MTL-News的long term success的一种方式。

目前blog由我和Kevin运营，白天我们在各自的公司上班，晚上回家更新blog。此外，我们也有各自在做side-project，还有贡献open source project。整个blog的搭建，我们在周末用了不到半个小时，既没有用服务器也没有专门申请域名，直接用了github的page和开源hubpress blog来上线我们的blog。简单粗暴让我们得以节省出大量的时间，来贡献blog内容和运营blog。

截至今天，blog运行一周，已经积累了1000的阅读量，这对于我们来说也是格外惊喜（由于我们针对的人群范围，我们并不期待能够有类似娱乐购物媒体那样的阅读访问量）。blog的页面停留时间平均在5min，意味着大多数读者基本上都阅读了整篇文章。我们绝多数文章都需要读者对于相关专业领域有一定了解，这也侧面验证了我们主要读者的经验和学识。我们在此也非常感谢读者，你们的支持是我们持续运作MTL-News最大的动力。

随着这一周的运行，我和Kevin体会到作为非金融专业的人士，在处理公司融资，并购，债务等各方面文章资源上的不足，以及无法腾出更多的时间来学习金融方面的知识（我们还拿了同学的cfa资料来学习）。因此，我们希望能找到一位有一定金融基础，特别是对Startup融资（从Angel直到IPO）感兴趣的“同学”加入我们。很遗憾，目前我们无法提供任何报酬，因此也不会强加任何任务给你。但，我们有源源不断的学习资源，希望你是一个self-discipline to work的朋友，加入我们，大家能够一起成长。更多信息请联系我们的微信，见文章底部。

